# Generated by Django 6.0.3 on 2026-05-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('readings', '0003_remove_healthreading_alert_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='status',
        ),
        migrations.AddField(
            model_name='alert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='reading',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readings.healthreading'),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(default='WARNING', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.CharField(default='Threshold exceeded', max_length=255),
        ),
    ]
