# Generated by Django 6.0.3 on 2026-05-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_remove_alert_alert_type_remove_alert_patient_and_more'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='reading',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='severity',
        ),
        migrations.AddField(
            model_name='alert',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(),
        ),
    ]
