# Generated by Django 6.0.3 on 2026-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_remove_alert_reading_remove_alert_severity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='patient',
        ),
        migrations.AddField(
            model_name='alert',
            name='patient_id',
            field=models.IntegerField(default=1),
        ),
    ]
