# Generated by Django 6.0.3 on 2026-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthreading',
            name='patient',
        ),
        migrations.AddField(
            model_name='healthreading',
            name='alert_level',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Critical', 'Critical')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='healthreading',
            name='medication_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthreading',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthreading',
            name='symptoms',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='healthreading',
            name='diastolic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='healthreading',
            name='systolic',
            field=models.IntegerField(),
        ),
    ]
