# Generated by Django 6.0.3 on 2026-05-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_remove_healthreading_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthreading',
            name='alert_level',
        ),
        migrations.RemoveField(
            model_name='healthreading',
            name='medication_taken',
        ),
        migrations.RemoveField(
            model_name='healthreading',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='healthreading',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='healthreading',
            name='patient_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='healthreading',
            name='reading_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthreading',
            name='diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthreading',
            name='glucose',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthreading',
            name='systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
